bench_name: "BrainX-22JFM"
bench_type: "forward"
query: "neuroscience"
max_results: 300
db: "pubmed"
threads: 5
BASE_URL: "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/"
PUB_BATCH_SIZE: 40  # 每次请求获取的最大文献数量，PubMed的限制
DATES_CONSIDERED: ["2019-Mar", "2019-Feb", "2019-Jan"]
start_year: 2019
end_year: 2019
start_month: 1
end_month: 3

segment_model: "gpt-4o"
flip_model: "gpt-4o"
validation_model: "gpt-4o"

seg_prompt: "prompts/forwards/split.md"
flip_prompt: "prompts/forwards/flip.md"
validation_prompt: "prompts/forwards/validation.md"


max_bench_size: 100

JOURNALS:
  - "Nature communications"
  - "The Journal of neuroscience : the official journal of the Society for Neuroscience"
  - "Proceedings of the National Academy of Sciences of the United States of America"
  - "Science advances"
  - "Neuron"
  - "Cell reports"
  - "eLife"
  - "Alzheimer's & dementia : the journal of the Alzheimer's Association"
  - "Nature neuroscience"
  - "The Journal of physiology"


LABEL_MATCHING_DIC : {
    "Nature communications": "NC",
    "The Journal of neuroscience : the official journal of the Society for Neuroscience": "JNeurosci",
    "Proceedings of the National Academy of Sciences of the United States of America": "PNAS",
    "Science advances": "Sci Adv",
    "Neuron": "Neuron",
    "Cell reports": "Cell Rep",
    "eLife": "eLife",
    "Alzheimer's & dementia : the journal of the Alzheimer's Association": "Alzheimer",
    "Nature neuroscience": "Nat. Neurosci",
    "The Journal of physiology": "J Physiol"
}


